name: Build and Deploy Website

on:
  push:
    branches: "master"
    paths: [".github/workflows/**", "Website/**"]
  workflow_dispatch:

jobs:
  build-deploy:
    if: |
      github.event_name == 'push' && github.ref == 'refs/heads/master' || 
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Website
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: projects/fe/package-lock.json
      - name: install dependencies
        run: npm run i
      - name: build and then have it start the deploy process
        run: npm run deploy
