<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageVersionOverrideEnabled>false</CentralPackageVersionOverrideEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Web.WebView2" Version="1.0.3719.77" />
    <PackageVersion Include="Octokit" Version="14.0.0" />
    <PackageVersion Include="MaterialSkinKR" Version="1.0.1" />
    <PackageVersion Include="System.IO.Hashing" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2705" />
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="2.4.0" />
    <PackageVersion Include="HtmlAgilityPack" Version="1.12.4" />
  </ItemGroup>
</Project>